new Card Added
Arman-ali-khan-786/CardUI pull request #138
Opened 2023-04-14 16:03 UTC by vijayNerdballer

made changes in the css, html file and assets folder.

2023-04-15 07:38 UTC, Arman-ali-khan-786 requested changes
you have written ui-17 it already exists change it to 18 and make the card responsive..

2023-04-15 10:32 UTC, vijayNerdballer commented
> you have written ui-17 it already exists change it to 18 and make the card responsive..

My mistake! Will let you know once I'm done

2023-04-15 15:38 UTC, vijayNerdballer commented
I have done some changes to make it better! can you verify?

2023-04-16 03:47 UTC, Arman-ali-khan-786 approved these changes

2023-04-16 03:48 UTC, merged