3d effect glass flip card ui added
Arman-ali-khan-786/CardUI pull request #177
Opened 2023-10-21 18:38 UTC by Recdata

2023-10-22 10:17 UTC, Arman-ali-khan-786 commented on index.html
please add your name and correct Ui number

2023-10-22 10:19 UTC, Arman-ali-khan-786 requested changes
First of all, get assigned then make a pr or else I won't accept it...
![Screenshot (682)](https://github.com/Arman-ali-khan-786/CardUI/assets/72055054/af57145f-b572-45af-a03b-2a632af11588)

add your name and do change the Ui number.

2023-10-23 06:23 UTC, Recdata commented
ok i will do the changes. please assign me to add my card ui.
Thanks

2023-10-29 13:55 UTC, Arman-ali-khan-786 requested changes
everything looks good i will merge it just pull the current changes and then make a pr again okk...

2023-11-04 09:35 UTC, merged