UI card 25
Arman-ali-khan-786/CardUI pull request #182
Opened 2023-10-23 07:04 UTC by ShiveshNandan

I created UI card 25

2023-10-28 13:54 UTC, Arman-ali-khan-786 commented
> I created UI card 25

it should be ui 24 check the main website ..

2023-10-28 13:56 UTC, Arman-ali-khan-786 requested changes
Card looks cool but ui is 24 and also source code should be written instead okk refer to below ss
![Screenshot (695)](https://github.com/Arman-ali-khan-786/CardUI/assets/72055054/c6d0a404-5c6f-4d12-9f2e-0e67d478276e)

do this changes rest all are good to be merged ...

2023-10-28 20:21 UTC, ShiveshNandan commented
i will change it, thanks for informing me !!

2023-10-29 13:44 UTC, Arman-ali-khan-786 approved these changes

2023-10-29 13:47 UTC, merged