Changed the fonts used in the project to make it attractive.
Arman-ali-khan-786/CardUI pull request #90
Opened 2022-10-09 19:03 UTC by IpsitaSenapati

I have changed the font styles across the website. I also have some ideas regarding website UI and a few card effects. Please assign me those too.

2022-10-10 10:52 UTC, Arman-ali-khan-786 commented
> I have changed the font styles across the website. I also have some ideas regarding website UI and a few card effects. Please assign me those too.

ok for that see issue #65

2022-10-10 10:53 UTC, Arman-ali-khan-786 requested changes
please fetch upstream(latest changes) before making a pr ok

2022-10-11 17:47 UTC, Arman-ali-khan-786 approved these changes

2022-10-11 17:47 UTC, merged

2022-10-13 05:30 UTC, zaidsidd360 commented
Hey @Arman-ali-khan-786 please look into PR #92. I fixed a bug introduced by @IpsitaSenapati in the index.css file which makes my card ui-10 break. Please merge the pr into master.